name: Test SSH via Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Test SSH via Cloudflare Tunnel
        run: |
          cloudflared access ssh --hostname ssh.asrhardi.dev -- ssh -o StrictHostKeyChecking=no root@localhost "echo '✅ SSH via tunnel OK on $(hostname)'"
